# (contiene la lista de criaturas y quién las derrotó, "-" o None significa que no fueron derrotadas según la tabla)
creatures = [
    {"name": "Ceto", "defeated_by": [],},
    {"name": "Tifón", "defeated_by": ["Zeus"],},
    {"name": "Equidna", "defeated_by": ["Argos Panoptes"],},
    {"name": "Dino", "defeated_by": [],},
    {"name": "Pefredo", "defeated_by": [],},
    {"name": "Enio", "defeated_by": [],},
    {"name": "Escila", "defeated_by": [],},
    {"name": "Caribdis", "defeated_by": [],},
    {"name": "Euríale", "defeated_by": [],},
    {"name": "Esteno", "defeated_by": [],},
    {"name": "Medusa", "defeated_by": ["Perseo"],},
    {"name": "Ladón", "defeated_by": ["Heracles"],},
    {"name": "Águila del Cáucaso", "defeated_by": [],},
    {"name": "Quimera", "defeated_by": ["Belerofonte"],},
    {"name": "Hidra de Lerna", "defeated_by": ["Heracles"],},
    {"name": "León de Nemea", "defeated_by": ["Heracles"],},
    {"name": "Esfinge", "defeated_by": ["Edipo"],},
    {"name": "Dragón de la Cólquida", "defeated_by": [],},
    {"name": "Cerbero", "defeated_by": [],},

    {"name": "Cerda de Cromión", "defeated_by": ["Teseo"],},
    {"name": "Ortro", "defeated_by": ["Heracles"],},
    {"name": "Toro de Creta", "defeated_by": ["Teseo"],},
    {"name": "Jabalí de Calidón", "defeated_by": ["Atalanta"],},
    {"name": "Carcinos", "defeated_by": [],},
    {"name": "Gerión", "defeated_by": ["Heracles"],},
    {"name": "Cloto", "defeated_by": [],},
    {"name": "Láquesis", "defeated_by": [],},
    {"name": "Átropos", "defeated_by": [],},
    {"name": "Minotauro de Creta", "defeated_by": ["Teseo"],},
    {"name": "Harpías", "defeated_by": [],},
    {"name": "Argos Panoptes", "defeated_by": ["Hermes"],},
    {"name": "Aves del Estínfalo", "defeated_by": [],},
    {"name": "Talos", "defeated_by": ["Medea"],},
    {"name": "Sirenas", "defeated_by": [],},
    {"name": "Pitón", "defeated_by": ["Apolo"],},
    {"name": "Cierva de Cerinea", "defeated_by": [],},
    {"name": "Basilisco", "defeated_by": [],},
    {"name": "Jabalí de Erimanto", "defeated_by": [],},
]
